### ISSUE TITLE
Chapter 2 Errata Notes

### ISSUE THREAD

**Issue by marknoble** [PacktPublishing/Creating-cross-platform-applications-with-Uno#4]
On page 31 of the book it discusses building HelloWorld.UWP but shows HelloWorld.Droid selected. On page 32, it shows a Pixel 2 emulator selected.  In this case we want the local machine.

Also, after following the instructions, I had an extra file called "HelloWorld.Uwp_TemporaryKey.pfx" in the folder that was causing the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Certificate could not be opened: HelloWorld.Uwp_TemporaryKey.pfx.
The specified network password is not correct.	HelloWorld.UWP			
```

I compared to the solution from Chapter 2 and found that, while the pfx cert was visible in the solution, the file had been deleted from the folder.

Deleting the pfx file cleared the error and allowed me to build successfully, but did result in this warning.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.	HelloWorld.UWP			

```

On page 33 the text states "If you have connected an Android phone to your computer, it will show up in the list of 
available target devices."  I had a Nokia 7.1 Android phone connected and it this Android One device did not show up in the list of available target devices.

On page 38, Hot Reload did not work on Save. I had to restart the app.

On page 42 I had to change the line as follows in order to get it to work:

`#elif HAS__UNO__WASM || __WASM__`

I was using Visual Studio 2022 Preview with Edge Dev as the browser and before the change it was showing the desktop message.

**Comment by marcelwgn** [comment]
Hi @marknoble , thank you for your feedback!

Regarding the screenshots, indeed it does not show UWP being selected and this could be confusing, thank you for mentioning this.

The certificate is missing as it is a default git ignored files (since it technically is a signing key and thus confidential). Having said that, I just created a new project using the steps and I was able to successfully run the app.

> On page 33 the text states "If you have connected an Android phone to your computer, it will show up in the list of
available target devices." I had a Nokia 7.1 Android phone connected and it this Android One device did not show up in the list of available target devices.

Have you enabled the developer options on your smartphone? This was not mentioned in the book, I added it to the new errata section in the readme file.

> On page 38, Hot Reload did not work on Save. I had to restart the app.

This seems to be an issue with the VS 2022, the book was written assuming VS 2019 and that worked fine. I'll look into this and respond here once I know more.

> On page 42 I had to change the line as follows in order to get it to work:
> #elif HAS__UNO__WASM || __WASM__

Thank you for mentioning this, I added this to the new errata section of the readme file.

**Comment by marcelwgn** [comment]
Regarding XAML Hot Reload, you need to enable XAML Intellisense for the XAML files for it to work with the UWP Head. You can find more information about this [here](https://platform.uno/docs/articles/get-started-vs.html#make-sure-xaml-intellisense-is-enabled). Also added this information to the errata in the readme file.
